version: 2

snapshot:
  version_template: "{{ .Version }}+SNAPSHOT-{{.ShortCommit}}"

builds:
  - skip: true

dockers:
  - build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=TORCH_INDEX_URL=https://download.pytorch.org/whl/cu126"
    dockerfile: .goreleaser.Dockerfile
    extra_files:
      - comfyui-entrypoint.sh
      - comfyui-install-nodes.sh
      - comfyui-install.sh
    image_templates:
      - "benfiola/comfyui:{{ .Version }}-cuda126"
    use: buildx
  - build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=TORCH_INDEX_URL=https://download.pytorch.org/whl/cpu"
    dockerfile: .goreleaser.Dockerfile
    extra_files:
      - comfyui-entrypoint.sh
      - comfyui-install-nodes.sh
      - comfyui-install.sh
    image_templates:
      - "benfiola/comfyui:{{ .Version }}-cpu"
    use: buildx
