version: 2

snapshot:
  version_template: "{{ .Version }}+SNAPSHOT-{{.ShortCommit}}"

builds:
  - skip: true

dockers:
  - build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--build-arg=TORCH_INDEX_URL=https://download.pytorch.org/whl/cu130"
      - "--build-arg=TORCH_VERSION=2.10.0"
      - "--build-arg=TORCHAUDIO_VERSION=2.10.0"
      - "--build-arg=TORCHVISION_VERSION=0.25.0"
    dockerfile: .goreleaser.Dockerfile
    extra_files:
      - comfyui-entrypoint.sh
      - comfyui-install-nodes.sh
      - comfyui-install.sh
    image_templates:
      - "benfiola/comfyui:{{ .Version }}-cuda130"
    use: buildx

